
SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE `account` ( `account_id` int(10) unsigned NOT NULL AUTO_INCREMENT, `algorithm` int(11) unsigned NOT NULL, `iterations` int(11) unsigned NOT NULL, `strategy` int(11) unsigned NOT NULL, `salt` binary(32) NOT NULL, `password` binary(32) NOT NULL, `email` varchar(64) COLLATE utf8mb4_bin NOT NULL, PRIMARY KEY (`account_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `gift` ( `gift_id` int(10) unsigned NOT NULL AUTO_INCREMENT, `wedding_id` int(10) unsigned NOT NULL, `name` varchar(45) COLLATE utf8mb4_bin NOT NULL, `description` varchar(45) COLLATE utf8mb4_bin NOT NULL, `price` int(10) unsigned NOT NULL, `number` int(10) unsigned NOT NULL, PRIMARY KEY (`gift_id`), KEY `fk_gift_wedding_idx` (`wedding_id`), CONSTRAINT `fk_gift_wedding` FOREIGN KEY (`wedding_id`) REFERENCES `wedding` (`wedding_id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `hotel` ( `hotel_id` int(10) unsigned NOT NULL AUTO_INCREMENT, `wedding_id` int(10) unsigned NOT NULL, `name` varchar(64) COLLATE utf8mb4_bin NOT NULL, `address` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL, `postal_code` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL, `city` varchar(64) COLLATE utf8mb4_bin NOT NULL, `latitude` decimal(10,8) NOT NULL, `longitude` decimal(11,8) NOT NULL, PRIMARY KEY (`hotel_id`), KEY `fk_hotel_wedding_idx` (`wedding_id`), CONSTRAINT `fk_hotel_wedding` FOREIGN KEY (`wedding_id`) REFERENCES `wedding` (`wedding_id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `invitation` ( `invitation_id` int(10) unsigned NOT NULL AUTO_INCREMENT, `unique_id` varchar(64) COLLATE utf8mb4_bin NOT NULL, `name` varchar(64) COLLATE utf8mb4_bin NOT NULL, `message` text COLLATE utf8mb4_bin NOT NULL, `rsvp` bit(1) NOT NULL, PRIMARY KEY (`invitation_id`), UNIQUE KEY `unique_id_UNIQUE` (`unique_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `message` ( `message_id` int(10) unsigned NOT NULL AUTO_INCREMENT, `wedding_id` int(10) unsigned NOT NULL, `sender` varchar(45) COLLATE utf8mb4_bin NOT NULL, `content` text COLLATE utf8mb4_bin NOT NULL, `timestamp` bigint(20) NOT NULL, PRIMARY KEY (`message_id`), KEY `fk_message_wedding_idx` (`wedding_id`), CONSTRAINT `fk_message_wedding` FOREIGN KEY (`wedding_id`) REFERENCES `wedding` (`wedding_id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `photo` ( `photo_id` int(10) unsigned NOT NULL AUTO_INCREMENT, `wedding_id` int(10) unsigned NOT NULL, `sha1` varchar(64) COLLATE utf8mb4_bin NOT NULL, `created` bigint(20) NOT NULL, PRIMARY KEY (`photo_id`), KEY `fk_photo_wedding_idx` (`wedding_id`), CONSTRAINT `fk_photo_wedding` FOREIGN KEY (`wedding_id`) REFERENCES `wedding` (`wedding_id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `reminder` ( `reminder` int(10) unsigned NOT NULL AUTO_INCREMENT, `wedding_id` int(10) unsigned NOT NULL, `email` varchar(64) COLLATE utf8mb4_bin NOT NULL, PRIMARY KEY (`reminder`), KEY `fk_reminder_wedding_idx` (`wedding_id`), CONSTRAINT `fk_reminder_wedding` FOREIGN KEY (`wedding_id`) REFERENCES `wedding` (`wedding_id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `schedule` ( `schedule_id` int(10) unsigned NOT NULL AUTO_INCREMENT, `wedding_id` int(10) unsigned NOT NULL, `start` bigint(20) NOT NULL, `end` bigint(20) NOT NULL, `name` varchar(45) COLLATE utf8mb4_bin NOT NULL, `location` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL, `description` text COLLATE utf8mb4_bin NOT NULL, PRIMARY KEY (`schedule_id`), KEY `fk_schedule_wedding_idx` (`wedding_id`), CONSTRAINT `fk_schedule_wedding` FOREIGN KEY (`wedding_id`) REFERENCES `wedding` (`wedding_id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `song` ( `song_id` int(10) unsigned NOT NULL AUTO_INCREMENT, `wedding_id` int(10) unsigned NOT NULL, `order` int(10) unsigned NOT NULL, `title` varchar(64) COLLATE utf8mb4_bin NOT NULL, `artist` varchar(64) COLLATE utf8mb4_bin NOT NULL, `url` varchar(256) COLLATE utf8mb4_bin NOT NULL, PRIMARY KEY (`song_id`), KEY `fk_song_wedding_idx` (`wedding_id`), CONSTRAINT `fk_song_wedding` FOREIGN KEY (`wedding_id`) REFERENCES `wedding` (`wedding_id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `video` ( `video_id` int(10) unsigned NOT NULL AUTO_INCREMENT, `wedding_id` int(10) unsigned NOT NULL, `url` varchar(256) COLLATE utf8mb4_bin NOT NULL, PRIMARY KEY (`video_id`), KEY `fk_video_wedding_idx` (`wedding_id`), CONSTRAINT `fk_video_wedding` FOREIGN KEY (`wedding_id`) REFERENCES `wedding` (`wedding_id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `wedding` ( `wedding_id` int(10) unsigned NOT NULL AUTO_INCREMENT, `account_id` int(11) unsigned NOT NULL, `latitude` decimal(10,8) NOT NULL, `longitude` decimal(11,8) NOT NULL, `date` bigint(20) NOT NULL, `hostname` varchar(64) COLLATE utf8mb4_bin NOT NULL, `template` varchar(32) COLLATE utf8mb4_bin DEFAULT NULL, PRIMARY KEY (`wedding_id`), UNIQUE KEY `account_id_UNIQUE` (`account_id`), UNIQUE KEY `hostname_UNIQUE` (`hostname`), CONSTRAINT `fk_wedding_account` FOREIGN KEY (`account_id`) REFERENCES `account` (`account_id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
SET FOREIGN_KEY_CHECKS = 1;
